# Generated by Django 3.1.4 on 2021-01-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210124_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
